Rpi uart
ubcrobomaster/vision pull request #36
Opened 2019-12-31 22:24 UTC by JoshMarangoni

2020-01-03 21:02 UTC, jamesrosstwo requested changes

2020-01-03 21:02 UTC, jamesrosstwo commented on raspberrypi/uart/uart.py
> +ser = serial.Serial("/dev/ttyS0", 115200)
I think some documentation would be good here. What is "/dev/ttyS0"?

Additionally, is the baud rate going to be used anywhere else? might be good to have the baud rate in a settings file

2020-01-03 21:02 UTC, jamesrosstwo commented on raspberrypi/uart/uart.py
> +	time.sleep(0.03)
Documentation would be good to explain the choice of `0.03` specifically

2020-01-04 00:55 UTC, pedramamani commented on raspberrypi/uart/uart.py
> +	time.sleep(0.03)
And place it in settings file

2020-02-09 20:44 UTC, cmcahoon01 approved these changes

2020-02-09 20:44 UTC, JoshMarangoni commented on raspberrypi/uart/uart.py
> +ser = serial.Serial("/dev/ttyS0", 115200)
That is the "file location" of the UART on Linux. Everything on Linux is a file

2020-02-09 20:47 UTC, jamesrosstwo commented on raspberrypi/uart/uart.py
> +ser = serial.Serial("/dev/ttyS0", 115200)
Yes, but the idea is to have that as a comment or something for those who don't know that

2020-03-08 19:30 UTC, jamesrosstwo approved these changes

2020-03-08 19:34 UTC, merged